<?php
require_once 'lib/Symfony/Component/ClassLoader/UniversalClassLoader.php';
use Symfony\Component\ClassLoader\UniversalClassLoader;

function btools_boot() {
  
  $loader = new UniversalClassLoader();
  
  $loader->registerNamespaces(array(
    'Symfony\Component' => __DIR__.'/lib',
  ));
  
  // You can search the include_path as a last resort.
  $loader->useIncludePath(true);
  $loader->register();
  
}